### ISSUE TITLE
InvalidType("a borrowed string"), meaning?

### ISSUE THREAD

**Issue by whoastonic** [mongodb/bson-rust#165]
While trying de-serialize a Bson, I get the error `InvalidType("a borrowed string")`

which i'm a little confused by... for context:

```rust
#[derive(serde::Serialize, serde::Deserialize)
struct NGC { name: String, post: String }

// serialze
let b: bson::Bson = bson::to_bson(&NGC { name: "Nene Sakura", post: "Game Programmer" })
  .expect("cannot convert to BSON");

// ... writes content to a document...

// de-serialize
let character = bson::from_bson<NGC>(b.clone())
  .expect("cannot convert to NGC") // where it errors out
```

At this moment, It seems that i'm doing something quite wrong, but the error doesn't really explain what I'm doing wrong... If anyone has any insight or encountered the same problem I would be glad if you can leave some suggestions 😄

**Comment by saghm** [comment]
I'm not able to reproduce your error. I compiled and ran the following code (which fixes a compiler errors in your example):

```rust
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Serialize, Deserialize)]
struct NGC {
    name: String,
    post: String,
}

fn main() {
    let b = bson::to_bson(&NGC {
        name: "Nene Sakura".into(),
        post: "Game Programmer".into(),
    })
    .expect("cannot convert to BSON");

    let character: NGC = bson::from_bson(b.clone()).expect("cannot convert to NGC");
    dbg!(character);
}
```

No errors occurred, and the output I got was what I expected:

```
[src/main.rs:17] character = NGC {
    name: "Nene Sakura",
    post: "Game Programmer",
}
```

Can you give a full example of the code you wrote that produces this error so I can reproduce it?

**Comment by whoastonic** [comment]
Ok, so while reviewing code and trying to debug the error code, I came up with this example

```rust
#[macro_use]
extern crate serde;
extern crate bson;

use std::fs::OpenOptions;
use std::io::{self, Read, Write};

#[derive(Debug, Serialize, Deserialize)]
struct ArrayContents<T> {
    contents: Vec<Contents<T>>
}

#[derive(Debug, Serialize, Deserialize)]
struct Contents<T> {
    content_name: String,
    content_value: T
}

#[derive(Debug, Serialize, Deserialize)]
struct NGC {
    name: &'static str,
    post: &'static str
}

fn main() {
    let mut file = OpenOptions::new()
        .write(true)
        .read(true)
        .create(true)
        .open("ngc_chars.bson")
        .expect("cannot open file");

    let mut bytes = Vec::new();

    let contents: Contents<NGC> = Contents {
        content_name: String::from("new-game-chars"),
        content_value: NGC {
            name: "Nene Sakura",
            post: "Game Programmer"
        }
    };

    let b = bson::to_bson(&ArrayContents { contents: vec![contents] })
        .expect("cannot convert to BSON");
    
    let doc = b.as_document().expect("cannot convert to doc");

    bson::encode_document(&mut bytes, doc)
        .expect("cannot send doc to bytes");
    
    file.write_all(&mut bytes)
        .expect("cannot write to file");
    
    dbg!(&b);

    let arr_contents = bson::from_bson::<ArrayContents<NGC>>(b)
        .expect("cannot convert content");

    dbg!(&arr_contents);
}
```

output log looking something like: 
```
[src/main.rs:54] &b = Document(OrderedDocument({"contents": Array([Document(OrderedDocument({"content_name": String("new-game-chars"), "content_value": Document(OrderedDocument({"name": String("Nene Sakura"), "post": String("Game Programmer")}))}))])}))
thread 'main' panicked at 'cannot convert content: InvalidType("a borrowed string")', src/main.rs:56:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

As you see it gave me the error `InvalidType("a borrowed string")`

while de-serializing:
```rust
#[derive(Debug, Serialize, Deserialize)]
struct NGC {
    name: &'static str,
    post: &'static str
}
```
But if I change this type into:
```rust
#[derive(Debug, Serialize, Deserialize)]
struct NGC {
    name: String,
    post: String,
}
```
everything runs smoothly giving me my desired output:
```
[src/main.rs:59] &arr_contents = ArrayContents {
    contents: [
        Contents {
            content_name: "new-game-chars",
            content_value: NGC {
                name: "Nene Sakura",
                post: "Game Programmer",
            },
        },
    ],
}
```

now that raise the question why can I serialize this type, but it has issues de-serializing? is this a general bug? or an issue with `serde` it-self?

**Comment by saghm** [comment]
Updating my example to use `&str` instead of `String` does give me the same error (regardless of whether I use the `'static` lifetime or a parameter:

```rust
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Serialize, Deserialize)]
struct NGC<'a> {
    name: &'a str,
    post: &'a str,
}

fn main() {
    let b = bson::to_bson(&NGC {
        name: "Nene Sakura".into(),
        post: "Game Programmer".into(),
    })
    .expect("cannot convert to BSON");

    let character: NGC = bson::from_bson(b.clone()).expect("cannot convert to NGC");
    dbg!(character);
}
```

```
thread 'main' panicked at 'cannot convert to NGC: InvalidType("a borrowed string")', src/main.rs:16:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Interestingly, converting this to use `serde_json` instead of BSON, instead of getting a runtime error, it gives a compiler error:

```rust
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Serialize, Deserialize)]
struct NGC<'a> {
    name: &'a str,
    post: &'a str,
}

fn main() {
    let b = serde_json::to_value(&NGC {
        name: "Nene Sakura".into(),
        post: "Game Programmer".into(),
    })
    .expect("cannot convert to JSON");

    let character: NGC = serde_json::from_value(b.clone()).expect("cannot convert to NGC");
    dbg!(character);
}
```

```
error: implementation of `_IMPL_DESERIALIZE_FOR_NGC::_serde::Deserialize` is not general enough
   --> src/main.rs:16:26
    |
16  |       let character: NGC = serde_json::from_value(b.clone()).expect("cannot convert to NGC");
    |                            ^^^^^^^^^^^^^^^^^^^^^^ implementation of `_IMPL_DESERIALIZE_FOR_NGC::_serde::Deserialize` is not general enough
    |
   ::: /home/saghm/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.110/src/de/mod.rs:531:1
    |
531 | / pub trait Deserialize<'de>: Sized {
532 | |     /// Deserialize this value from the given Serde deserializer.
533 | |     ///
534 | |     /// See the [Implementing `Deserialize`][impl-deserialize] section of the
...   |
569 | |     }
570 | | }
    | |_- trait `_IMPL_DESERIALIZE_FOR_NGC::_serde::Deserialize` defined here
    |
    = note: `NGC<'_>` must implement `_IMPL_DESERIALIZE_FOR_NGC::_serde::Deserialize<'0>`, for any lifetime `'0`...
    = note: ...but `NGC<'_>` actually implements `_IMPL_DESERIALIZE_FOR_NGC::_serde::Deserialize<'1>`, for some specific lifetime `'1`
```

Based on the fact that `serde_json` doesn't allow this either, it seems like the fact that this doesn't work is correct. Getting a compiler error is definitely better than a runtime error though, so it's definitely worth looking into whether we can have that happen as well.

**Comment by patrickfreed** [comment]
I filed RUST-511 to track the work on improving `from_bson`'s error diagnostics. Thanks for filing this issue!

**Comment by whoastonic** [comment]
> 
> 
> I filed [RUST-511](https://jira.mongodb.org/browse/RUST-511) to track the work on improving `from_bson`'s error diagnostics. Thanks for filing this issue!

No problem, I was glad I was able to help, and hope this issue will be solved soon
